[env:nibble-rp2350]
extends = rp2040_base
; Force the community platform and Pico 2 board
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
board_level = extra
board_build.core = earlephilhower
upload_protocol = picotool

; Add our variants files to the include and src paths
build_flags = ${rp2040_base.build_flags} 
  -D PRIVATE_HW
  -I variants/retia-nibble/nibble-rp2350
  -D DEBUG_RP2040_PORT=Serial
  -D HW_SPI1_DEVICE
lib_deps =
  ${rp2040_base.lib_deps}
debug_build_flags = ${rp2040_base.build_flags}, -g
debug_tool = cmsis-dap ; for e.g. Picotool
