[env:nibble-rp2350]
extends = pico2
board_level = extra
upload_protocol = picotool

; Add our variants files to the include and src paths
build_flags = ${pico2.build_flags} 
  -D PRIVATE_HW
  -I variants/retia-nibble/nibble-rp2350
  -D DEBUG_RP2040_PORT=Serial
  -D HW_SPI1_DEVICE

lib_deps =
  ${pico2.lib_deps}

debug_build_flags = ${pico2.build_flags}, -g
debug_tool = cmsis-dap ; for e.g. Picotool
